# Generated by Django 5.2.1 on 2026-05-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSQIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('q1_bedtime', models.CharField(blank=True, max_length=10)),
                ('q2_sleep_latency_minutes', models.IntegerField(blank=True, null=True)),
                ('q3_wakeup_time', models.CharField(blank=True, max_length=10)),
                ('q4_sleep_hours', models.FloatField(blank=True, null=True)),
                ('sleep_quality', models.IntegerField()),
                ('sleep_latency', models.IntegerField()),
                ('sleep_duration', models.IntegerField()),
                ('sleep_efficiency', models.IntegerField()),
                ('sleep_disturbance', models.IntegerField()),
                ('sleeping_medication', models.IntegerField()),
                ('daytime_dysfunction', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
