# Generated by Django 5.2.1 on 2026-08-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psqi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetabolicScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='年齡')),
                ('gender', models.CharField(max_length=20, verbose_name='性別')),
                ('height', models.FloatField(verbose_name='身高')),
                ('weight', models.FloatField(verbose_name='體重')),
                ('bmi', models.FloatField(verbose_name='BMI')),
                ('sleep_hours', models.FloatField(verbose_name='每日平均睡眠時數')),
                ('sleep_category', models.CharField(max_length=50, verbose_name='睡眠分類')),
                ('smoking', models.CharField(max_length=30, verbose_name='抽菸狀況')),
                ('exercise', models.CharField(max_length=30, verbose_name='運動狀況')),
                ('alcohol', models.CharField(max_length=30, verbose_name='飲酒狀況')),
                ('betel_nut', models.CharField(max_length=30, verbose_name='檳榔狀況')),
                ('diet', models.CharField(max_length=30, verbose_name='飲食狀況')),
                ('waist', models.FloatField(blank=True, null=True, verbose_name='腰圍')),
                ('risk_level', models.CharField(max_length=30, verbose_name='風險層級')),
                ('risk_factors', models.TextField(blank=True, verbose_name='風險因素')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '代謝症候群篩檢紀錄',
                'verbose_name_plural': '代謝症候群篩檢紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='psqiresponse',
            options={'verbose_name': 'PSQI 睡眠品質問卷', 'verbose_name_plural': 'PSQI 睡眠品質問卷'},
        ),
    ]
